# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-08 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': True},
        ),
    ]
